sudo: required
services:
  - docker

before_install:
  - docker build -t zafatar/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true zafatar/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-eu-central-1-569739914161"
  bucket_path: "docker-react-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY